name: Run Say Hello

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v4 

      - name: Set up Make
        run: sudo apt-get install make

      - name: Run say-hello
        run: make say-hello

      - name: Hello form Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release4
